language: php

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5

services:
  - mongodb
  - memcached

before_install:
 - phpenv config-add ./unit-tests/ci/memcache.ini
 - phpenv config-add ./unit-tests/ci/mongo.ini
 - ./unit-tests/ci/install_prereqs.sh
 - ./unit-tests/ci/setup_dbs.sh

before_script:
 - git submodule --quiet update --init --recursive
 - (cd php-tests/library/Mustache; git checkout master )
 - (cd php-tests/library/Twig; git checkout master )
 - (cd unit-tests/engines/; git clone -q git://github.com/bobthecow/mustache.php.git & git clone -q git://github.com/fabpot/Twig.git & wait)
 - (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j2 && sudo make install && phpenv config-add ../unit-tests/ci/phalcon.ini)
 - ulimit -c unlimited || true

script:
 - $(phpenv which php) ./unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml
 - phpenv config-rm $APCEXT
 - export PREVDIR=$(pwd)
 - cd ~; svn co svn://svn.lighttpd.net/xcache/trunk xcache-trunk; cd xcache-trunk
 - phpize && ./configure --enable-xcache && make && make install
 - phpenv config-add xcache.ini
 - cd $PREVDIR
 - echo "flush_all" | nc localhost 11211
 - $(phpenv which php) ./unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml ./unit-tests/CacheTest.php

after_failure:
 - sudo apt-get -qq install gdb
 - ./unit-tests/ci/after_failure.sh

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
    - nikos@phalconphp.com